name: Deploy Frontend
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy-frontend-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull from GitHub repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/privacy-patrol/multi-step-form
            git pull --rebase
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use
            npm install
            npm run build
            pm2 reload 11